[package]
name = "echs_bash_parser"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "echs_bash_parser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.35"
tree-sitter = "0.24"
tree-sitter-bash = "0.23"
